services:
    # Event Listeners/Subscribers
    mdb_document.event_listener.document_subscriber:
        class: MDB\DocumentBundle\EventListener\DocumentSubscriber
        tags:
            - { name: kernel.event_subscriber }

    # Managers
    mdb_document.manager.document.default:
        class: MDB\DocumentBundle\Document\DocumentManager
        arguments: ["@event_dispatcher", "@doctrine.odm.mongodb.document_manager", %mdb_document.model.document.class% ]


    mdb_document.manager.file.default:
        class: MDB\DocumentBundle\Document\FileManager
        arguments: ["@event_dispatcher","@doctrine.odm.mongodb.document_manager", %mdb_document.model.file.class% ]

    # Form Type
    mdb_document.form_type.document:
        class: MDB\DocumentBundle\Form\Type\DocumentType
        arguments: [%mdb_document.model.document.class%]
        tags:
            - { name: form.type, alias: mdb_document_document }

    mdb_document.form_type.file:
        class: MDB\DocumentBundle\Form\Type\FileType
        arguments: [%mdb_document.model.file.class%]
        tags:
            - { name: form.type, alias: mdb_document_file }


    mdb_document.form_type.pre_linked_document:
        class: MDB\DocumentBundle\Form\Type\PreLinkedDocumentType
        arguments: [%mdb_document.model.document.class%]
        tags:
            - { name: form.type, alias: mdb_document_pre_linked_document }

    mdb_document.form_factory.document:
        class: MDB\DocumentBundle\Form\Factory\FormFactory
        arguments: ["@form.factory", "mdb_document_document", "mdb_document_document" ]

    mdb_document.form_factory.file:
        class: MDB\DocumentBundle\Form\Factory\FormFactory
        arguments: ["@form.factory", "mdb_document_file", "mdb_document_file" ]

    # Others
    mdb_document.file_response_factory:
        class: MDB\DocumentBundle\Factory\FileResponseFactory
        calls:
            - [ setContainer, [ @service_container ] ]

    mdb_document.partial_controller:
        class: MDB\DocumentBundle\Controller\PartialController

    liip_imagine.data.loader.grid_fs:
        class: Liip\ImagineBundle\Imagine\Data\Loader\GridFSLoader
        arguments: [ @liip_imagine, @doctrine.odm.mongodb.document_manager, %mdb_document.model.file.class%]
        tags:
            - { name: liip_imagine.data.loader, loader: grid_fs}

    mdb_document.serializer.handler.thumbnail:
        class: MDB\DocumentBundle\Serializer\Handler\ThumbnailHandler
        arguments: [@request, @liip_imagine.controller, @liip_imagine.cache.manager]
        scope: request
        tags:
            - { name: jms_serializer.handler, type: Thumbnail, direction: serialization, format: json, method: serialize }
