services:
#     mdb_document_document_manager:
    mdb_document_document_manager:
        class: MDB\DocumentBundle\Document\DocumentManager
        arguments: ["@doctrine.odm.mongodb.document_manager", "MDB\DocumentBundle\Document\Document" ]

    mdb_document.file_response_factory:
        class: MDB\DocumentBundle\Factory\FileResponseFactory
        calls:
            - [ setContainer, [ @service_container ] ]