<?php

namespace MDB\DocumentBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository as ODMDocumentRepository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends ODMDocumentRepository
{
    public function createIsActiveQueryBuilder()
    { 
        return $this->createQueryBuilder('MDB\DocumentBundle\Document\Document');
    }
    
    public function findDocumentsByClassAndObjectId($className, $objectId)
    {
        if(!$objectId instanceof \MongoId)
            $objectId = new \MongoId($objectId);

        return $this->createQueryBuilder('MDB\DocumentBundle\Document\Document')
            ->field('links.class')->equals($className)
            ->field('links.objectId')->equals($objectId)
            ->getQuery()
            ->execute();
    }

    
}