<?php

namespace MDB\DocumentBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository as ODMDocumentRepository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends ODMDocumentRepository
{
    public function createIsActiveQueryBuilder()
    { 
        return $this->createQueryBuilder('MDB\DocumentBundle\Document\Document');
    }
}