# mdb_document_document_index:
#     pattern: /documents
#     defaults:  { _controller: MDBDocumentBundle:Document:index }

# mdb_document_document_new:
#     pattern: /documents/new
#     defaults: { _controller: MDBDocumentBundle:Document:new }

# mdb_document_document_file:
#     pattern: /documents/file
#     defaults: { _controller: MDBDocumentBundle:Document:file }

# mdb_document_document_show:
#     pattern: /documents/show/{id}
#     defaults: { _controller: MDBDocumentBundle:Document:show }

# mdb_document_document_edit:
#     pattern: /documents/edit/{id}
#     defaults: { _controller: MDBDocumentBundle:Document:edit }

# mdb_document_document_delete:
#     pattern: /documents/delete/{id}
#     defaults: { _controller: MDBDocumentBundle:Document:delete }

mdbdocument_document:
    resource: "@MDBDocumentBundle/Controller/DocumentController.php"
    type: annotation

mdbdocument_file:
    resource: "@MDBDocumentBundle/Controller/FileController.php"
    type: annotation
    prefix: /files
